Update pripravi_podatke.yml

diff --git a/.github/workflows/pripravi_podatke.yml b/.github/workflows/pripravi_podatke.yml
--- a/.github/workflows/pripravi_podatke.yml
+++ b/.github/workflows/pripravi_podatke.yml
@@ -94,16 +94,20 @@ jobs:
         
     - name: Remove from Git and add to DVC
       run: |
+        set -e
         git rm --cached 'data/processed/reference_data.csv'
-        
+        echo 'data/processed/reference_data.csv' >> .gitignore
 
-    - name: Remove from Git and add to DVC
-      run: |
-        dvc add 'data/processed/reference_data.csv'
-        dvc push -r origin
-        git add .
-        git commit -m "Update changes"
+        git add .gitignore
+        git commit -m "stop tracking data/processed/reference_data.csv and add to .gitignore"
         git push
+        dvc add 'data/processed/reference_data.csv'
+        dvc push -v || { echo "DVC push failed"; exit 1; }
+
+        git add data/processed/reference_data.csv.dvc data/processed/.gitignore
+        git commit -m "track data/processed/reference_data.csv with DVC"
+        git push
+
        
         
         
